#include "pipeline_object.h"
#include "d3d_helper.h"
#include "d3d12shader.h"
#include "dxcapi.h"
#include "render_proxy.h"
#include <assert.h>
#include <cmath>

static void CheckResult(HRESULT result, Microsoft::WRL::ComPtr<ID3DBlob> error_blob)
{
	if (FAILED(result))
	{
		if (error_blob)
		{
			OutputDebugStringA((char*)error_blob->GetBufferPointer());
		}
	}
}

static void CompileShaingModel6(LPCWSTR* pszArgs, int args_num, LPCWSTR source_file, Microsoft::WRL::ComPtr<IDxcBlob>& pShader)
{
	Microsoft::WRL::ComPtr<IDxcUtils> pUtils;
	Microsoft::WRL::ComPtr<IDxcCompiler3> pCompiler;
	DxcCreateInstance(CLSID_DxcUtils, IID_PPV_ARGS(&pUtils));
	DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(&pCompiler));

	// Create default include handler. 
	Microsoft::WRL::ComPtr<IDxcIncludeHandler> pIncludeHandler;
	pUtils->CreateDefaultIncludeHandler(&pIncludeHandler);

	Microsoft::WRL::ComPtr<IDxcBlobEncoding> pSource = nullptr;
	pUtils->LoadFile(source_file, nullptr, &pSource);
	DxcBuffer Source;
	Source.Ptr = pSource->GetBufferPointer();
	Source.Size = pSource->GetBufferSize();
	Source.Encoding = DXC_CP_ACP;
	Microsoft::WRL::ComPtr<IDxcResult> pResults;
	pCompiler->Compile(
		&Source,                // Source buffer.
		pszArgs,                // Array of pointers to arguments.
		args_num,      // Number of arguments.
		pIncludeHandler.Get(),        // User-provided interface to handle #include directives (optional).
		IID_PPV_ARGS(&pResults) // Compiler output status, buffer, and errors.
	);
	Microsoft::WRL::ComPtr<IDxcBlobUtf8> pErrors = nullptr;
	pResults->GetOutput(DXC_OUT_ERRORS, IID_PPV_ARGS(&pErrors), nullptr);
	// Note that d3dcompiler would return null if no errors or warnings are present.
	// IDxcCompiler3::Compile will always return an error buffer, but its length
	// will be zero if there are no warnings or errors.
	if (pErrors != nullptr && pErrors->GetStringLength() != 0)
		OutputDebugStringA(pErrors->GetStringPointer());

	HRESULT hrStatus;
	pResults->GetStatus(&hrStatus);
	if (FAILED(hrStatus))
	{
		OutputDebugStringA("Compilation Failed\n");
		return;
	}

	//
	// Save shader binary.
	//
	Microsoft::WRL::ComPtr<IDxcBlobUtf16> pShaderName = nullptr;
	pResults->GetOutput(DXC_OUT_OBJECT, IID_PPV_ARGS(&pShader), &pShaderName);
	if (pShader != nullptr)
	{
		FILE* fp = NULL;

		_wfopen_s(&fp, pShaderName->GetStringPointer(), L"wb");
		fwrite(pShader->GetBufferPointer(), pShader->GetBufferSize(), 1, fp);
		fclose(fp);
	}

	//
	// Save pdb.
	//
	Microsoft::WRL::ComPtr<IDxcBlob> pPDB = nullptr;
	Microsoft::WRL::ComPtr<IDxcBlobUtf16> pPDBName = nullptr;
	pResults->GetOutput(DXC_OUT_PDB, IID_PPV_ARGS(&pPDB), &pPDBName);
	{
		FILE* fp = NULL;

		// Note that if you don't specify -Fd, a pdb name will be automatically generated.
		// Use this file name to save the pdb so that PIX can find it quickly.
		_wfopen_s(&fp, pPDBName->GetStringPointer(), L"wb");
		fwrite(pPDB->GetBufferPointer(), pPDB->GetBufferSize(), 1, fp);
		fclose(fp);
	}

}

DefaultGraphicPipeline::DefaultGraphicPipeline()
{

}

void DefaultGraphicPipeline::InitShaders()
{
	{
		LPCWSTR hlsl_file_name = L"./shader/default/vertex_shader.hlsl";
		LPCWSTR pszArgs[] =
		{
			hlsl_file_name,            // shader source file name for error reporting and for PIX shader source view.  
			L"-E", L"VSMain",              // Entry point.
			L"-T", L"vs_6_0",            // Target.
			L"-Zi",L"-Qembed_debug",        // Enable debug information (slim format)
#if defined(_DEBUG)
			L"-Od",
#endif
			//L"-D", L"MYDEFINE=1",        // A single define.
			L"-Fd", L"./shader/default/vertex_shader.pdb",     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
			L"-Fo",L"./shader/default/vertex_shader.cso"
		};
		Microsoft::WRL::ComPtr<IDxcBlob> shader_out;
		CompileShaingModel6(pszArgs, _countof(pszArgs), hlsl_file_name, shader_out);
		shader_out.As(&m_vertex_shader);
	}

	{
		LPCWSTR hlsl_file_name = L"./shader/default/pixel_shader.hlsl";
		LPCWSTR pszArgs[] =
		{
			hlsl_file_name,            // shader source file name for error reporting and for PIX shader source view.  
			L"-E", L"PSMain",              // Entry point.
			L"-T", L"ps_6_0",            // Target.
			L"-Zi", L"-Qembed_debug",                     // Enable debug information (slim format)
#if defined(_DEBUG)
			L"-Od",
#endif
			//L"-D", L"MYDEFINE=1",        // A single define.
			L"-Fd", L"./shader/default/pixel_shader.pdb",     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
			L"-Fo",L"./shader/default/pixel_shader.cso"
		};
		Microsoft::WRL::ComPtr<IDxcBlob> shader_out;
		CompileShaingModel6(pszArgs, _countof(pszArgs), hlsl_file_name, shader_out);
		shader_out.As(&m_pixel_shader);
	}

}

void DefaultGraphicPipeline::InitRootSignature()
{
	assert(m_device);
	CD3DX12_ROOT_SIGNATURE_DESC rootSignatureDesc;
	rootSignatureDesc.Init(0, nullptr, 0, nullptr, D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT);
	Microsoft::WRL::ComPtr<ID3DBlob> serialized_signature_desc;
	Microsoft::WRL::ComPtr<ID3DBlob> error;
	ThrowIfFailed(D3D12SerializeRootSignature(&rootSignatureDesc, D3D_ROOT_SIGNATURE_VERSION_1, &serialized_signature_desc, &error));
	ThrowIfFailed(m_device->GetDevice()->CreateRootSignature(0, serialized_signature_desc->GetBufferPointer(), serialized_signature_desc->GetBufferSize(), IID_PPV_ARGS(&m_root_signature)));

}
void DefaultGraphicPipeline::InitPSO()
{
	assert(m_device);
	D3D12_INPUT_ELEMENT_DESC inputElementDescs[] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};

	// Describe and create the graphics pipeline state object (PSO).
	D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc = {};
	psoDesc.InputLayout = { inputElementDescs, _countof(inputElementDescs) };
	psoDesc.pRootSignature = m_root_signature.Get();
	psoDesc.VS = CD3DX12_SHADER_BYTECODE(m_vertex_shader.Get());
	psoDesc.PS = CD3DX12_SHADER_BYTECODE(m_pixel_shader.Get());
	psoDesc.RasterizerState = CD3DX12_RASTERIZER_DESC(D3D12_DEFAULT);
	psoDesc.BlendState = CD3DX12_BLEND_DESC(D3D12_DEFAULT);
	psoDesc.DepthStencilState = CD3DX12_DEPTH_STENCIL_DESC(D3D12_DEFAULT);
	psoDesc.SampleMask = UINT_MAX;
	psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
	psoDesc.NumRenderTargets = 1;
	psoDesc.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
	psoDesc.DSVFormat = DXGI_FORMAT_D32_FLOAT;
	psoDesc.SampleDesc.Count = 1;
	ThrowIfFailed(m_device->GetDevice()->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(&m_pipeline_state)));
}

void DefaultGraphicPipeline::InitResources()
{
	;
}

void DefaultGraphicPipeline::Init( std::shared_ptr<D3DHelper::Device> device)
{
	m_device = device;
	InitShaders();
	InitRootSignature();
	InitPSO();
	InitResources();
}

void DefaultGraphicPipeline::SetRootSignature(Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> command_list, const ViewInfo* p_view, const RenderProxy* proxy, 
	D3D12_GPU_DESCRIPTOR_HANDLE* stack_bottom)
{
	command_list->SetGraphicsRootSignature(m_root_signature.Get());
}

void DefaultGraphicPipeline::CommitDescriptors(D3DHelper::StaticDescriptorStack(&param_stacks)[D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES])
{
	/*
	for (int i = 0; i < D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES; i++)
	{
		param_stacks[i].push_back(m_heaps[i], 0, m_heaps[i].GetDescriptorNum());
	}
	*/
}

void DefaultGraphicPipeline::Draw(Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> command_list,
	D3DHelper::StaticDescriptorStack(&param_stacks)[D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES],
	int buffer_index,
	const ViewInfo* p_view,
	const RenderProxy* proxy)
{
	auto triangle_render_proxy = dynamic_cast<const TriangleRenderProxy*>(proxy);
	assert(triangle_render_proxy);

	command_list->RSSetViewports(1, &p_view->m_viewport);
	command_list->RSSetScissorRects(1, &p_view->m_scissor_rect);
	command_list->OMSetRenderTargets(1, &p_view->render_target_view, false, &p_view->depth_stencil_view);
	command_list->SetPipelineState(m_pipeline_state.Get());
	//D3D12_GPU_DESCRIPTOR_HANDLE param_stack_bottom[] = { param_stacks[0].GetTopGPU(),};
	triangle_render_proxy->CommitParams(command_list, param_stacks);
	SetRootSignature(command_list, p_view,proxy,nullptr);
	CommitDescriptors(param_stacks);
	command_list->DrawInstanced(triangle_render_proxy->GetVertexCountPerInstance(), 1, 0, 0);
}



void StaticMeshGraphicPipeline::InitShaders()
{
	{
		LPCWSTR hlsl_file_name = L"./shader/triangle/vertex_shader.hlsl";
		LPCWSTR pszArgs[] =
		{
			hlsl_file_name,            // shader source file name for error reporting and for PIX shader source view.  
			L"-E", L"VSMain",              // Entry point.
			L"-T", L"vs_6_0",            // Target.
			L"-Zi",L"-Qembed_debug",        // Enable debug information (slim format)
#if defined(_DEBUG)
			L"-Od",
#endif
			//L"-D", L"MYDEFINE=1",        // A single define.
			L"-Fd", L"./shader/triangle/vertex_shader.pdb",     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
			L"-Fo",L"./shader/triangle/vertex_shader.cso"
		};
		Microsoft::WRL::ComPtr<IDxcBlob> shader_out;
		CompileShaingModel6(pszArgs, _countof(pszArgs), hlsl_file_name, shader_out);
		shader_out.As(&m_vertex_shader);
	}

	{
		LPCWSTR hlsl_file_name = L"./shader/triangle/pixel_shader.hlsl";
		LPCWSTR pszArgs[] =
		{
			hlsl_file_name,            // shader source file name for error reporting and for PIX shader source view.  
			L"-E", L"PSMain",              // Entry point.
			L"-T", L"ps_6_0",            // Target.
			L"-Zi", L"-Qembed_debug",                     // Enable debug information (slim format)
#if defined(_DEBUG)
			L"-Od",
#endif
			//L"-D", L"MYDEFINE=1",        // A single define.
			L"-Fd", L"./shader/triangle/pixel_shader.pdb",     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
			L"-Fo",L"./shader/triangle/pixel_shader.cso"
		};
		Microsoft::WRL::ComPtr<IDxcBlob> shader_out;
		CompileShaingModel6(pszArgs, _countof(pszArgs), hlsl_file_name, shader_out);
		shader_out.As(&m_pixel_shader);
	}

}

void StaticMeshGraphicPipeline::InitRootSignature()
{
	assert(m_device);
	CD3DX12_ROOT_PARAMETER rootParameters[2];
	rootParameters[0].InitAsConstants(sizeof(ViewBuffer) / 4, 0, 0, D3D12_SHADER_VISIBILITY_VERTEX);
	rootParameters[1].InitAsConstants(sizeof(BatchBuffer) / 4, 1, 0, D3D12_SHADER_VISIBILITY_VERTEX);

	CD3DX12_ROOT_SIGNATURE_DESC rootSignatureDesc;
	rootSignatureDesc.Init(_countof(rootParameters), rootParameters, 0, nullptr, D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT);
	Microsoft::WRL::ComPtr<ID3DBlob> serialized_signature_desc;
	Microsoft::WRL::ComPtr<ID3DBlob> error;
	ThrowIfFailed(D3D12SerializeRootSignature(&rootSignatureDesc, D3D_ROOT_SIGNATURE_VERSION_1, &serialized_signature_desc, &error));
	ThrowIfFailed(m_device->GetDevice()->CreateRootSignature(0, serialized_signature_desc->GetBufferPointer(), serialized_signature_desc->GetBufferSize(), IID_PPV_ARGS(&m_root_signature)));
}

void StaticMeshGraphicPipeline::SetRootSignature(Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> command_list, const ViewInfo* p_view, const RenderProxy* proxy, 
	D3D12_GPU_DESCRIPTOR_HANDLE* stack_bottom)
{
	command_list->SetGraphicsRootSignature(m_root_signature.Get());

	ViewBuffer view_buffer;
	view_buffer.view_transform = p_view->view_matrix;
	view_buffer.project_transform = p_view->project_matrix;
	view_buffer.viewport_size = { int(p_view->m_viewport.Width),int(p_view->m_viewport.Height) };
	BatchBuffer batch_buffer;
	batch_buffer.world_transform = proxy->world_transform;

	command_list->SetGraphicsRoot32BitConstants(0, sizeof(ViewBuffer) / 4, &view_buffer, 0);
	command_list->SetGraphicsRoot32BitConstants(1, sizeof(BatchBuffer) / 4, &batch_buffer, 0);
}

MeshGaussianPipeline::MeshGaussianPipeline():DefaultGraphicPipeline(), pipeline_data_dirty(true)
{

}

void MeshGaussianPipeline::InitShaders()
{
	{
		LPCWSTR hlsl_file_name = L"./shader/ms_gaussian_splatting/GaussianMS.hlsl";
		LPCWSTR pszArgs[] =
		{
			hlsl_file_name,            // shader source file name for error reporting and for PIX shader source view.  
			L"-E", L"main",              // Entry point.
			L"-T", L"ms_6_5",            // Target.
			L"-Zi", L"-Qembed_debug",                     // Enable debug information (slim format)
#if defined(_DEBUG)
			L"-Od",
#endif
			//L"-D", L"MYDEFINE=1",        // A single define.
			L"-Fd", L"./shader/ms_gaussian_splatting/GaussianMS.pdb",     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
			L"-Fo",L"./shader/ms_gaussian_splatting/GaussianMS.cso"
		};
		Microsoft::WRL::ComPtr<IDxcBlob> shader_out;
		CompileShaingModel6(pszArgs, _countof(pszArgs), hlsl_file_name, shader_out);
		shader_out.As(&m_vertex_shader);
	}

	{
		LPCWSTR hlsl_file_name = L"./shader/ms_gaussian_splatting/GaussianPS.hlsl";
		LPCWSTR pszArgs[] =
		{
			hlsl_file_name,            // shader source file name for error reporting and for PIX shader source view.  
			L"-E", L"PSMain",              // Entry point.
			L"-T", L"ps_6_0",            // Target.
			L"-Zi",L"-Qembed_debug",                      // Enable debug information (slim format)
#if defined(_DEBUG)
			L"-Od",
#endif
			//L"-D", L"MYDEFINE=1",        // A single define.
			L"-Fd", L"./shader/ms_gaussian_splatting/GaussianPS.pdb",     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
			L"-Fo",L"./shader/ms_gaussian_splatting/GaussianPS.cso",
			L"-Qstrip_reflect",          // Strip reflection into a separate blob. 
		};
		Microsoft::WRL::ComPtr<IDxcBlob> shader_out;
		CompileShaingModel6(pszArgs, _countof(pszArgs), hlsl_file_name, shader_out);
		shader_out.As(&m_pixel_shader);
	}
}

void MeshGaussianPipeline::InitPSO()
{
	D3D12_BLEND_DESC blend_desc = CD3DX12_BLEND_DESC(D3D12_DEFAULT);
	blend_desc.RenderTarget[0].BlendEnable = true;
	blend_desc.RenderTarget[0].LogicOpEnable = FALSE;
	blend_desc.RenderTarget[0].SrcBlend = D3D12_BLEND_SRC_ALPHA;
	blend_desc.RenderTarget[0].DestBlend = D3D12_BLEND_INV_SRC_ALPHA;
	blend_desc.RenderTarget[0].BlendOp = D3D12_BLEND_OP_ADD;
	blend_desc.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
	blend_desc.RenderTarget[0].SrcBlendAlpha = D3D12_BLEND_ONE;
	blend_desc.RenderTarget[0].DestBlendAlpha = D3D12_BLEND_ZERO;
	blend_desc.RenderTarget[0].BlendOpAlpha = D3D12_BLEND_OP_ADD;
	blend_desc.RenderTarget[0].LogicOp = D3D12_LOGIC_OP_NOOP;

	//depth:disable Depth Wirte & enable Depth Test
	D3D12_DEPTH_STENCIL_DESC depth_stencil_desc;
	depth_stencil_desc.DepthEnable = true;
	depth_stencil_desc.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ZERO;
	depth_stencil_desc.DepthFunc = D3D12_COMPARISON_FUNC_LESS;
	depth_stencil_desc.StencilEnable = false;

	D3DX12_MESH_SHADER_PIPELINE_STATE_DESC pso_desc = {};
	pso_desc.pRootSignature = m_root_signature.Get();
	pso_desc.MS = CD3DX12_SHADER_BYTECODE(m_vertex_shader.Get());
	pso_desc.PS = CD3DX12_SHADER_BYTECODE(m_pixel_shader.Get());
	pso_desc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
	pso_desc.NumRenderTargets = 1;
	pso_desc.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
	pso_desc.DSVFormat = DXGI_FORMAT_D32_FLOAT;
	pso_desc.RasterizerState = CD3DX12_RASTERIZER_DESC(D3D12_DEFAULT);
	pso_desc.RasterizerState.CullMode = D3D12_CULL_MODE_NONE; // do not cull back!!
	pso_desc.BlendState = blend_desc;         // transparent
	pso_desc.DepthStencilState = depth_stencil_desc;
	pso_desc.SampleMask = UINT_MAX;
	pso_desc.SampleDesc = DefaultSampleDesc();

	auto psoStream = CD3DX12_PIPELINE_MESH_STATE_STREAM(pso_desc);
	D3D12_PIPELINE_STATE_STREAM_DESC streamDesc;
	streamDesc.pPipelineStateSubobjectStream = &psoStream;
	streamDesc.SizeInBytes = sizeof(psoStream);
	ThrowIfFailed(m_device->GetDevice()->CreatePipelineState(&streamDesc, IID_PPV_ARGS(&m_pipeline_state)));
}

void MeshGaussianPipeline::InitResources()
{
	//create resource
	auto gaussian_texture_desc = CD3DX12_RESOURCE_DESC::Tex2D(DXGI_FORMAT_R32_FLOAT, GAUSSIAN_TEXTURE_SIZE.x, GAUSSIAN_TEXTURE_SIZE.y, 1, GAUSSIAN_TEXTURE_LOD, 1, 0);
	ThrowIfFailed(m_device->GetDevice()->CreateCommittedResource(&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_DEFAULT), D3D12_HEAP_FLAG_NONE, &gaussian_texture_desc,
		D3D12_RESOURCE_STATE_COPY_DEST, nullptr, IID_PPV_ARGS(&gaussian_texture_buffer)));

	const UINT64 uploadBufferSize = GetRequiredIntermediateSize(gaussian_texture_buffer.Get(), 0, 1);
	ThrowIfFailed(m_device->GetDevice()->CreateCommittedResource(&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_UPLOAD),D3D12_HEAP_FLAG_NONE,
		&CD3DX12_RESOURCE_DESC::Buffer(uploadBufferSize),D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&gaussian_texture_upload_buffer)));

	//init descriptor heap
	D3D12_DESCRIPTOR_HEAP_DESC heap_desc{};
	heap_desc.NumDescriptors = 1;
	heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
	heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
	m_heaps[D3D12_DESCRIPTOR_HEAP_TYPE::D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV].Init(heap_desc,m_device);

	//init view
	D3D12_SHADER_RESOURCE_VIEW_DESC gaussian_texture_srv_desc;
	gaussian_texture_srv_desc.Format = DXGI_FORMAT_R32_FLOAT;
	gaussian_texture_srv_desc.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
	gaussian_texture_srv_desc.Texture2D.MipLevels = GAUSSIAN_TEXTURE_LOD;
	gaussian_texture_srv_desc.Texture2D.PlaneSlice = 0;
	gaussian_texture_srv_desc.Texture2D.MostDetailedMip = 0;
	gaussian_texture_srv_desc.Texture2D.ResourceMinLODClamp = 0;
	gaussian_texture_srv_desc.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
	m_device->GetDevice()->CreateShaderResourceView(gaussian_texture_buffer.Get(), &gaussian_texture_srv_desc,
		m_heaps[D3D12_DESCRIPTOR_HEAP_TYPE::D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV][0]);

	//init cpu data
	cpu_gaussian_texture_buffer.resize(GAUSSIAN_TEXTURE_SIZE.x * GAUSSIAN_TEXTURE_SIZE.y * 2);
	{
		float mean_x = GAUSSIAN_TEXTURE_SIZE.x / 2;
		float mean_y = GAUSSIAN_TEXTURE_SIZE.y / 2;
		float axis_x = mean_x - 0.5f;
		float axis_y = mean_y - 0.5f;
		float cov_inv_00 = 2 * std::log(255) / (axis_x * axis_x);
		float cov_inv_11 = 2 * std::log(255) / (axis_y * axis_y);
		for (int x = 0; x < GAUSSIAN_TEXTURE_SIZE.x; x++)
		{
			for (int y = 0; y < GAUSSIAN_TEXTURE_SIZE.y; y++)
			{
				float delta_x = x + 0.5f - mean_x;
				float delta_y = y + 0.5f - mean_y;
				cpu_gaussian_texture_buffer[y * GAUSSIAN_TEXTURE_SIZE.x + x] = std::exp(-0.5 * (cov_inv_00 * delta_x * delta_x + cov_inv_11 * delta_y * delta_y));
			}
		}
	}
	int cur_lod_offset = GAUSSIAN_TEXTURE_SIZE.x * GAUSSIAN_TEXTURE_SIZE.y;
	int last_lod_offset = 0;
	for (int lod = 1; lod < GAUSSIAN_TEXTURE_LOD; lod++)
	{
		int cur_lod_size_x = (GAUSSIAN_TEXTURE_SIZE.x >> lod);
		int cur_lod_size_y = (GAUSSIAN_TEXTURE_SIZE.y >> lod);
		int last_lod_size_x = (GAUSSIAN_TEXTURE_SIZE.x >> lod);
		int last_lod_size_y = (GAUSSIAN_TEXTURE_SIZE.y >> lod);
		for (int x = 0; x < cur_lod_size_x; x++)
		{
			for (int y = 0; y < cur_lod_size_y; y++)
			{
				float value=cpu_gaussian_texture_buffer[last_lod_offset + (y * 2) * last_lod_size_x + (x * 2)];
				value = std::fmaxf(value, cpu_gaussian_texture_buffer[last_lod_offset + (y * 2) * last_lod_size_x + (x * 2 + 1)]);
				value = std::fmaxf(value, cpu_gaussian_texture_buffer[last_lod_offset + (y * 2 + 1) * last_lod_size_x + (x * 2)]);
				value = std::fmaxf(value, cpu_gaussian_texture_buffer[last_lod_offset + (y * 2 + 1) * last_lod_size_x + (x * 2 + 1)]);
				cpu_gaussian_texture_buffer[cur_lod_offset + y * cur_lod_size_x + x] = value;
			}
		}
		last_lod_offset = cur_lod_offset;
		cur_lod_offset += cur_lod_size_x * cur_lod_size_y;
	}

}

void MeshGaussianPipeline::UpdatePipelineData(Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> command_list)
{
	assert(pipeline_data_dirty);
	D3D12_SUBRESOURCE_DATA textureData = {};
	textureData.pData = cpu_gaussian_texture_buffer.data();
	textureData.RowPitch = GAUSSIAN_TEXTURE_SIZE.x * sizeof(float);
	textureData.SlicePitch = textureData.RowPitch * GAUSSIAN_TEXTURE_SIZE.y * 2;
	UpdateSubresources(command_list.Get(), gaussian_texture_buffer.Get(), gaussian_texture_upload_buffer.Get(), 0, 0, 1, &textureData);
	command_list->ResourceBarrier(1, &CD3DX12_RESOURCE_BARRIER::Transition(gaussian_texture_buffer.Get(), D3D12_RESOURCE_STATE_COPY_DEST, D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE));
	pipeline_data_dirty = false;
}

void MeshGaussianPipeline::InitRootSignature()
{
	D3D12_STATIC_SAMPLER_DESC sampler = CD3DX12_STATIC_SAMPLER_DESC();
	sampler.Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
	sampler.AddressU = D3D12_TEXTURE_ADDRESS_MODE_BORDER;
	sampler.AddressV = D3D12_TEXTURE_ADDRESS_MODE_BORDER;
	sampler.AddressW = D3D12_TEXTURE_ADDRESS_MODE_BORDER;
	sampler.MipLODBias = 0;
	sampler.MaxAnisotropy = 0;
	sampler.ComparisonFunc = D3D12_COMPARISON_FUNC_NEVER;
	sampler.BorderColor = D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK;
	sampler.MinLOD = 0.0f;
	sampler.MaxLOD = GAUSSIAN_TEXTURE_LOD;
	sampler.ShaderRegister = 0;
	sampler.RegisterSpace = 0;
	sampler.ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	CD3DX12_ROOT_PARAMETER rootParameters[3];
	rootParameters[0].InitAsConstants(sizeof(ViewBuffer) / 4, 0, 0, D3D12_SHADER_VISIBILITY_ALL);
	rootParameters[1].InitAsConstants(sizeof(BatchBuffer) / 4, 1, 0, D3D12_SHADER_VISIBILITY_MESH);
	CD3DX12_DESCRIPTOR_RANGE DescRange[1];
	DescRange[0].Init(D3D12_DESCRIPTOR_RANGE_TYPE_SRV, 3, 0);//points srv + clusters srv + texture srv
	rootParameters[2].InitAsDescriptorTable(_countof(DescRange), DescRange, D3D12_SHADER_VISIBILITY_ALL);

	CD3DX12_ROOT_SIGNATURE_DESC rootSignatureDesc;
	rootSignatureDesc.Init(_countof(rootParameters), rootParameters, 1, &sampler, D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT);
	Microsoft::WRL::ComPtr<ID3DBlob> serialized_signature_desc;
	Microsoft::WRL::ComPtr<ID3DBlob> error;
	ThrowIfFailed(D3D12SerializeRootSignature(&rootSignatureDesc, D3D_ROOT_SIGNATURE_VERSION_1, &serialized_signature_desc, &error));
	ThrowIfFailed(m_device->GetDevice()->CreateRootSignature(0, serialized_signature_desc->GetBufferPointer(), serialized_signature_desc->GetBufferSize(), IID_PPV_ARGS(&m_root_signature)));
}

void MeshGaussianPipeline::SetRootSignature(Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> command_list, const ViewInfo* p_view, const RenderProxy* proxy, 
	D3D12_GPU_DESCRIPTOR_HANDLE* stack_bottom)
{
	command_list->SetGraphicsRootSignature(m_root_signature.Get());

	ViewBuffer view_buffer;
	view_buffer.view_transform = p_view->view_matrix;
	view_buffer.project_transform = p_view->project_matrix;
	view_buffer.viewport_size = { int(p_view->m_viewport.Width),int(p_view->m_viewport.Height) };
	view_buffer.focal = p_view->focal;
	BatchBuffer batch_buffer;
	batch_buffer.world_transform = proxy->world_transform;

	command_list->SetGraphicsRoot32BitConstants(0, sizeof(ViewBuffer) / 4, &view_buffer, 0);
	command_list->SetGraphicsRoot32BitConstants(1, sizeof(BatchBuffer) / 4, &batch_buffer, 0);
	command_list->SetGraphicsRootDescriptorTable(2, stack_bottom[D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV]);

	auto gaussian_render_proxy = dynamic_cast<const GaussianRenderProxy*>(proxy);
	assert(gaussian_render_proxy);
	
}

void MeshGaussianPipeline::CommitDescriptors(D3DHelper::StaticDescriptorStack(&param_stacks)[D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES])
{
	param_stacks[D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV].push_back(m_heaps[D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV], 
		0, m_heaps[D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV].GetDescriptorNum());
}

void MeshGaussianPipeline::Draw(Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> command_list,
	D3DHelper::StaticDescriptorStack(&param_stacks)[D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES],
	int buffer_index,
	const ViewInfo* p_view,
	const RenderProxy* proxy)
{
	auto gaussian_render_proxy = dynamic_cast<const GaussianRenderProxy*>(proxy);
	assert(gaussian_render_proxy);
	if (pipeline_data_dirty)
	{
		UpdatePipelineData(command_list);
	}
	
	command_list->RSSetViewports(1, &p_view->m_viewport);
	command_list->RSSetScissorRects(1, &p_view->m_scissor_rect);
	command_list->OMSetRenderTargets(1, &p_view->render_target_view, false, &p_view->depth_stencil_view);
	command_list->SetPipelineState(m_pipeline_state.Get());
	D3D12_GPU_DESCRIPTOR_HANDLE stack_bottom[2]{ param_stacks[D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV].GetTopGPU(), D3D12_GPU_DESCRIPTOR_HANDLE() };
	SetRootSignature(command_list, p_view, proxy, stack_bottom);
	gaussian_render_proxy->CommitParams(command_list,param_stacks);
	CommitDescriptors(param_stacks);

	Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList6> command_list6;
	command_list.As(&command_list6);
	assert(command_list6);
	command_list6->DispatchMesh(proxy->GetVertexCountPerInstance(), 1, 1);
}